### ISSUE TITLE
Bad response

### ISSUE THREAD

**Issue by darshilchapadia** [Sispheor/MMM-quote-of-the-day#1]
Sometimes, API response is in string format instead of object.

**Comment by Sispheor** [comment]
Can you give an output example?

**Comment by darshilchapadia** [comment]
`"{\"quoteText\":\"Freedom is what you do with what\\'s been done to you.\", \"quoteAuthor\":\"Jean-Paul Sartre\", \"senderName\":\"\", \"senderLink\":\"\", \"quoteLink\":\"http://forismatic.com/en/d714592782/\"}"`

I am not able to parse this string.

**Comment by The-Exterminator** [comment]
I get this error, the lang: da

[13.01.2021 14:08.56.848] [LOG]   MMM-quote-of-the-day received a socket notification: GET_QUOTE - Payload: [object Object]
[13.01.2021 14:08.56.930] [LOG]   {
    "quoteText": "You can complain because roses have thorns, or you can rejoice because thorns have roses. ",
    "quoteAuthor": " Ziggy",
    "senderName": "",
    "senderLink": "",
    "quoteLink": "http://forismatic.com/en/a1538942bb/"
}
[13.01.2021 14:08.59.330] [ERROR] Error
    at /home/pi/MagicMirror/modules/MMM-quote-of-the-day/node_modules/google-translate-api/index.js:105:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'BAD_REQUEST'
}
